server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

security:
  jwt:
    secret: dev-secret-change-this-to-32-bytes-minimum-1234
    whitelist:
      - /auth/

management:
  endpoints:
    web:
      exposure:
        include: health,info


