version: '3.9'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-product
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: productdb
      MYSQL_USER: productuser
      MYSQL_PASSWORD: productpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend

  postgres:
    image: postgres:16
    container_name: postgres-shared
    environment:
      POSTGRES_PASSWORD: pgpass
      POSTGRES_USER: pguser
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - backend

  redis:
    image: redis:7-alpine
    container_name: redis-cart
    ports:
      - "6379:6379"
    networks:
      - backend

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-payment
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Your_password123"
    ports:
      - "1433:1433"
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Your_password123 -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

networks:
  backend:
    driver: bridge

volumes:
  mysql_data:
  postgres_data:


